### ISSUE TITLE
feature / JH / Chat_develop

### ISSUE THREAD

**Issue by baejeonghyun23** [ProjectTeam-Ultimatum/springboot#73]
##Description
> submodule 적용시킨 프로젝트에 채팅작업물 불러오기

## ToDoList
- [ ] submodule 적용시킨 develop 브랜치에 원래 작업하던 브랜치 pull 당겨오기
- [ ] todo2
- [ ] todo3

**Comment by leeeunjae1** [comment]
👍🏻
